pipenv: upgrade dev dependencies for compatibility with python3.8
```
  File "/home/travis/virtualenv/python3.8.0/lib/python3.8/site-packages/importlib_metadata/__init__.py", line 179, in from_name
    dists = resolver(name)
  File "<frozen importlib._bootstrap_external>", line 1382, in find_distributions
  File "/home/travis/virtualenv/python3.8.0/lib/python3.8/importlib/metadata.py", line 379, in find_distributions
    found = cls._search_paths(context.pattern, context.path)
AttributeError: 'str' object has no attribute 'pattern'
The command "pipenv run pytest --cov=freesurfer_stats --cov-report=term-missing --cov-fail-under=100" exited with 1.
```
https://travis-ci.org/github/fphammerle/freesurfer-stats/jobs/683704327